version: "3"
name: "levels-db"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:?}
      MYSQL_DATABASE: levels
      MYSQL_USER: levels
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:?}
    ports:
      - "${DATABASE_PORT:?}:${DATABASE_PORT:?}"
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10