version: "3"
name: "levels"

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        - DOMAIN=${DOMAIN:?DOMAIN}
        - PORT=${PORT:?PORT}
    ports:
      - "${PORT}:443"
    volumes:
      - ./:/levels
    depends_on:
      - frontend
      - backend
      
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:?DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: levels
      MYSQL_USER: levels
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  migrate:
    image: flyway/flyway:latest
    command: ["-url=jdbc:mysql://mysql:${DATABASE_PORT}/levels", "-user=root", "-password=${DATABASE_ROOT_PASSWORD}", "migrate"]
    volumes:
      - ./docker/migrate:/flyway/sql
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    command: ["npm", "run", "start"]

  backend:
    container_name: backend
    restart: on-failure
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    command: ["npm", "run", "start"]