CREATE TABLE [IF NOT EXISTS] guild_users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    guildId VARCHAR(255),
    userId VARCHAR(255),
    username VARCHAR(255),
    discriminator VARCHAR(4),
    tag VARCHAR(255),
    avatarUrl VARCHAR(255),
    rank INT,
    level INT,
    xp INT,
    averageXp INT,
    hourlyXp INT,
    dailyXp INT,
    weeklyXp INT,
    monthlyXp INT,
    messages INT,
    hourlyMsg INT,
    dailyMsg INT,
    weeklyMsg INT,
    monthlyMsg INT
)